---
title: "KSProject"
author: "Wuge Li"
date: "2024-02-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r include=FALSE}
library(readxl)
library(dplyr)
library(ggplot2)
library(gridExtra)

# Data cleaning
KSdata <- read_excel("KS_data.xlsx", sheet = 2)

KSD <- KSdata[3:16, ]
KSD1 <- KSD |>
  select(c("...1", "Total number of references"))
colnames(KSD1) <- c("KDC", "total")

KSI <- KSdata[19:23, ]
KSI1 <- KSI |>
  select(c("...1", "Total number of references"))
colnames(KSI1) <- c("KII", "total")

CI <- KSdata[26:31, ]
CI1 <- CI |>
  select(c("...1", "Total number of references"))
colnames(CI1) <- c("CI", "total")

Age <- KSdata[34:37, ]
Age1 <- Age |>
  select(c("...1", "Total number of references"))
colnames(Age1) <- c("age", "total")

# Plot of the data
CI1$color_value <- CI1$total / sum(CI1$total)
p1 <- ggplot(CI1, aes(x = total, y = reorder(CI, total), fill = color_value)) +
  geom_bar(stat="identity", width = 0.7) +
  scale_fill_gradient(low="lightgrey", high="darkblue") +
  theme_classic() +
  theme(legend.position = "none",
        plot.margin = margin(t = 10, r = 5, b = 10, l = 0, unit = "pt")) +
  labs(x = NULL, y = " KS Caregiver 
Impacts")
p1 <- p1 + theme(
  axis.title.y = element_text(margin = margin(t = 0, r = 59, b = 0, l = 10, unit = "pt"))
)

KSI1$color_value <- KSI1$total / sum(KSI1$total)
p2 <- ggplot(KSI1, aes(x = total, y = reorder(KII, total), fill = color_value)) +
  geom_bar(stat="identity", width = 0.7) +
  scale_fill_gradient(low="grey", high="darkgreen") +
  theme_classic() +
  theme(legend.position = "none",
        axis.title.y = element_text(),
        plot.margin = margin(t = 10, r = 5, b = 10, l = 0, unit = "pt")) +
  labs(x = NULL, y = "KS Individual 
Impacts")
p2 <- p2 + theme(
  axis.title.y = element_text(margin = margin(t = 0, r = 144, b = 0, l = 10, unit = "pt"))
)

KSD1$color_value <- KSD1$total / sum(KSD1$total)
p3 <- ggplot(KSD1, aes(x = total, y = reorder(KDC, total), fill = color_value)) +
  geom_bar(stat="identity", width = 0.7) +
  scale_fill_gradient(low="lightgrey", high="darkred") +
  theme_classic() +
  theme(legend.position = "none",
        axis.title.y = element_text(),
        plot.margin = margin(t = 10, r = 5, b = 10, l = 0, unit = "pt")) +
  labs(x = NULL, y = "KS Defining 
Features")
p3 <- p3 + theme(
  axis.title.y = element_text(margin = margin(t = 0, r = 74, b = 0, l = 10, unit = "pt"))
)

Age1$color_value <- Age1$total / sum(Age1$total)
p4 <- ggplot(Age1, aes(x = total, y = reorder(age, total), fill = color_value)) +
  geom_bar(stat="identity", width = 0.7) +
  scale_fill_gradient(low="lightgrey", high="purple") +
  theme_classic() +
  theme(legend.position = "none",
        axis.title.y = element_text(),
        plot.margin = margin(t = 10, r = 5, b = 10, l = 0, unit = "pt")) +
  labs(x = NULL, y = "Developmental Age 
Groups")
p4 <- p4 + theme(
  axis.title.y = element_text(margin = margin(t = 0, r = 8, b = 0, l = 10, unit = "pt"))
)

p4 <- p4 + 
  labs(x = "References")

p5 <- grid.arrange(p3, p2, p1, p4, ncol = 1, heights = c(2, 1, 1, 1))
```

```{r bar-plot, fig.width=8, fig.height = 8, echo = FALSE, fig.cap = "Total references bar chart."}
grid.arrange(p5)
```





