---
title: "**Kleefstra Syndrome Disease Concept Model**"
author:
  - Teaching Fellow - Minh Thu Bui
  - Supervisor - Professor Masanao Yajima
  - Wuge Li, Maysen Pagan, Amie Thomas
output: 
  bookdown::pdf_document2:
    toc: false
    number_sections: true
---

# Project Background and Objectives

# Visualizations

## Total Frequencies Bar Plot

### Analysis

## Age Group Symptoms Frequencies Heatmap
```{r, echo=FALSE}
library(ggpubr)
library(tidyverse)
library(gridExtra)

#load in data
KS_data <- read.csv("KS_lifespan.csv")
KS_data$X <- str_replace(KS_data$X, " impact", "")
KS_data$X <- str_replace(KS_data$X, " and ", " & ")

#defining concepts subset data
concepts <- KS_data[2:15, -6]

#rename for ease
concepts <- rename(concepts, Symptoms = `X`)
concepts <- rename(concepts, `< 2` = `under.2.years.of.age..infancy...N.16.`,
                   `2-4` = `X2.4.years.of.age...early.childhood...N.15.`,
                   `5-11` = `X5.11.years.of.age..late.childhood...N.13.`,
                   `12-17` = `X12.17.years.of.age..adolescence.and.teenage.years...N.6.`)

#find sum of individual columns
conc_csums <- colSums(concepts[ , -1])

#divide cell values by column total for frequency
#put frequency values in new columns
concepts <- concepts |>
  mutate(
    `Under 2` = `< 2` / conc_csums[1],
    `2-4 Years` = `2-4` / conc_csums[2],
    `5-11 Years` = `5-11` / conc_csums[3],
    `12-17 Years` = `12-17` / conc_csums[4]
  )

#format for graphing
concepts_2 <- select(concepts, -`< 2`, -`2-4`, -`5-11`, -`12-17`)
concepts_2 <- pivot_longer(concepts_2, cols = c(`Under 2`, `2-4 Years`, `5-11 Years`, `12-17 Years`), names_to = "age", values_to = "Frequencies")

concepts_2$age <- factor(concepts_2$age, levels = c("Under 2", "2-4 Years", "5-11 Years", "12-17 Years"))

#heatmap
heatmap_1 <- ggplot(concepts_2, aes(x=age, y=Symptoms, fill= Frequencies)) +
   geom_tile(color = "black") +  
   geom_tile(color = "white", fill = NA) +  
   geom_tile(color = "white", fill = NA) +  
   geom_text(aes(label = sprintf("%.2f", Frequencies)), color = "black", size = 5) +  # Add text labels
   scale_fill_gradient(low="white", high="darkred") + 
   labs(x = NULL, y = "Symptoms")+
   scale_x_discrete(expand = c(0, 0), position = 'top', labels = c("Under 2", limits = c(0, 1))) +
   theme_minimal() +  
   theme(panel.grid = element_blank())+
   theme(
    panel.grid = element_blank(),
    axis.text.y = element_text(family = "Times New Roman", size = 20),
    axis.text.x = element_text(family = "Times New Roman", size = 16),
    plot.title = element_text(family = "Times New Roman", size = 10), 
    legend.title = element_text(family = "Times New Roman", size = 14), 
    legend.text = element_text(family = "Times New Roman", size = 14),
    axis.title.y = element_text(family = "Times New Roman", face = "bold", size = 22)
  )

heatmap_1

#individual impacts subset data
ind_impacts <- KS_data[18:21, -6]

ind_impacts <- rename(ind_impacts, Impacts = `X`)
ind_impacts <- rename(ind_impacts, `< 2` = `under.2.years.of.age..infancy...N.16.`,
                   `2-4` = `X2.4.years.of.age...early.childhood...N.15.`,
                   `5-11` = `X5.11.years.of.age..late.childhood...N.13.`,
                   `12-17` = `X12.17.years.of.age..adolescence.and.teenage.years...N.6.`)


#find sum of individual columns
ind_csums <- colSums(ind_impacts[ ,-1])

#divide cell values by column total for frequency
#put frequency values in new columns
ind_impacts <- ind_impacts |>
  mutate(
    `Under 2` = `< 2` / ind_csums[1],
    `2-4 Years` = `2-4` / ind_csums[2],
    `5-11 Years` = `5-11` / ind_csums[3],
    `12-17 Years` = `12-17` / ind_csums[4]
  )

#format for graphing
ind_impacts_2 <- select(ind_impacts, -`< 2`, -`2-4`, -`5-11`, -`12-17`)
ind_impacts_2 <- pivot_longer(ind_impacts_2, cols = c(`Under 2`, `2-4 Years`, `5-11 Years`, `12-17 Years`), names_to = "age", values_to = "Frequencies")

ind_impacts_2$age <- factor(ind_impacts_2$age, levels = c("Under 2", "2-4 Years", "5-11 Years", "12-17 Years"))


#heatmap
heatmap_2 <- ggplot(ind_impacts_2, aes(x=age, y=Impacts, fill= Frequencies)) +
   geom_tile(color = "black") +  
   geom_tile(color = "white", fill = NA) + 
   geom_tile(color = "white", fill = NA) +  
   geom_text(aes(label = sprintf("%.2f", Frequencies)), color = "black", size = 5) +  # Add text labels
   scale_fill_gradient(low = "white", high = "darkgreen", limit = c(0,1))+
   labs(x = NULL, y = "Impacts on the Individual")+
   scale_x_discrete(expand = c(0, 0),position = 'top') +
   theme_minimal() +  
   theme(panel.grid = element_blank())+
  theme(
    panel.grid = element_blank(),
    axis.text.y = element_text(family = "Times New Roman", size = 20),
    axis.text.x = element_text(family = "Times New Roman", size = 18),
    plot.title = element_text(family = "Times New Roman", size = 10), 
    legend.title = element_text(family = "Times New Roman", size = 14), 
    legend.text = element_text(family = "Times New Roman", size = 14),
    axis.title.y = element_text(family = "Times New Roman", face = "bold", size = 22),
    plot.margin = margin(t = 0, r = .1, b = 0, l = .1, unit = "cm")
  )

heatmap_2

#caregiver impacts subset data
care_impacts <- KS_data[24:27, -6]

care_impacts <- rename(care_impacts, Impacts = `X`)
care_impacts <- rename(care_impacts, `< 2` = `under.2.years.of.age..infancy...N.16.`,
                   `2-4` = `X2.4.years.of.age...early.childhood...N.15.`,
                   `5-11` = `X5.11.years.of.age..late.childhood...N.13.`,
                   `12-17` = `X12.17.years.of.age..adolescence.and.teenage.years...N.6.`)

#find sum of individual columns
care_csums <- colSums(care_impacts[ ,-1])

#divide cell values by column total for frequency
#put frequency values in new columns
care_impacts <- care_impacts |>
  mutate(
    `Under 2` = `< 2` / care_csums[1],
    `2-4 Years` = `2-4` / care_csums[2],
    `5-11 Years` = `5-11` / care_csums[3],
    `12-17 Years` = `12-17` / care_csums[4]
  )

#format for graphing
care_impacts_2 <- select(care_impacts, -`< 2`, -`2-4`, -`5-11`, -`12-17`)
care_impacts_2 <- pivot_longer(care_impacts_2, cols = c(`Under 2`, `2-4 Years`, `5-11 Years`, `12-17 Years`), names_to = "age", values_to = "Frequencies")

care_impacts_2$age <- factor(care_impacts_2$age, levels = c("Under 2", "2-4 Years", "5-11 Years", "12-17 Years"))


#heatmap (looks a little childish. Want to look more sophisticated. Perhaps interactive)
heatmap_3 <- ggplot(care_impacts_2, aes(x=age, y=Impacts, fill= Frequencies)) +
   geom_tile(color = "black") +  
   geom_tile(color = "white", fill = NA) +  
   geom_text(aes(label = sprintf("%.2f", Frequencies)), color = "black", size = 5) +  #add numbers on heatmap
   scale_fill_gradient(low="white", high="darkblue", limits = c(0,1)) + 
   labs(x = NULL, y = "Impacts on the Caregiver")+
   scale_x_discrete(expand = c(0, 0),position = 'top') +
   theme_minimal() +  
   theme(panel.grid = element_blank())+
   theme(
    panel.grid = element_blank(),
    axis.text.y = element_text(family = "Times New Roman", size = 20),
    axis.text.x = element_text(family = "Times New Roman", size = 18),
    plot.title = element_text(family = "Times New Roman", size = 10), 
    legend.title = element_text(family = "Times New Roman", size = 14), 
    legend.text = element_text(family = "Times New Roman", size = 14),
    axis.title.y = element_text(family = "Times New Roman", face = "bold", size = 22),
    plot.margin = margin(t = 0, r = .1, b = 0, l = .1, unit = "cm")
   )
heatmap_3
     
```

```{r, fig.width=20}
#plots in same place
grid.arrange(heatmap_1, arrangeGrob(heatmap_2, heatmap_3), ncol=2)
```


#test

### Analysis



## Age Group Frequencies Bar Plot

### Analysis

### Conclusion
